[project]
name = "dramabox"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
  "accelerate>=0.25.0",
  "av>=12.0.0",
  "bitsandbytes>=0.45.0",
  "einops>=0.7.0",
  "hf-xet>=1.5.0",
  "huggingface-hub>=0.20.0,<2.0",
  "peft>=0.7.0",
  "pyyaml>=6.0",
  "resemble-perth",
  "safetensors>=0.4.0",
  "sentencepiece>=0.1.99",
  "soundfile>=0.12.0",
  "spaces>=0.30.0",
  "torch==2.8.0",
  "torchaudio==2.8.0",
  "transformers>=4.45.0",
]
dynamic = ["version"]

[project.optional-dependencies]
gradio = [
  "gradio==5.7.1",
  "pydantic==2.10.6",

]

[dependency-groups]
dev = [
  "ipykernel>=7.2.0",
  "ipython>=9.13.0",
  "nbwipers>=0.6.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "src/__init__.py"

[tool.hatch.build.targets.wheel]
packages = ["src", "ltx2/ltx_core", "ltx2/ltx_pipelines", "ltx2/ltx_trainer"]

[tool.hatch.build.targets.wheel.sources]
"src" = "dramabox"
"ltx2/ltx_core" = "ltx_core"
"ltx2/ltx_pipelines" = "ltx_pipelines"
"ltx2/ltx_trainer" = "ltx_trainer"

[tool.ruff]
line-length = 160
target-version = "py312"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "D",
  "S",
  "ANN",
  "COM",  # trailing commas are not needed
  "ERA",  # allow commented code
  "ISC001",  # conflicts with formatter
  "PTH",  # allow opening files without pathlib
  "TRY003",  # allow exception messages as string literals
  "TD",  # allow FIXME messages
  "FIX",  # allow FIXME messages
  "RUF002",  # allow ambiguous characters in docstrings
  "RUF003",  # allow ambiguous characters in comments
  "PLC0415",  # allow import outside top level
  "PD",  # most PD rules are not helpful
  "C901",  # complexity lints
  "PLR0912",
  "PLR0915",
  "PLR2004",  # magic values
  "N",  # naming
  "FBT",  # boolean trap
  "PLR0913",  # arguments in fucntion
  "G004",  # f string in log
  "T20",  # allow print
  "PGH003",  # type error suppression
]
extend-select = [
  "PD002",  # pandas-use-of-inplace-argument
  "PD007",  # pandas-use-of-dot-ix
  "PD101",  # pandas-nunique-constant-series-check
]

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[tool.uv.sources]
torch = [
  { index = "pytorch-cu126", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchvision = [
  { index = "pytorch-cu126", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchaudio = [
  { index = "pytorch-cu126", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
resemble-perth = { git = "https://github.com/resemble-ai/Perth.git", rev = "master" }
